import React, { useRef, useEffect } from 'react';
import { Edit3, Sparkles } from 'lucide-react';

export function ReviewCard({ reviewText, onChangeText, isAutoGenerated }) {
  const textareaRef = useRef(null);

  // Auto-adjust textarea height to fit content smoothly without scrollbars
  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${Math.max(120, textareaRef.current.scrollHeight)}px`;
    }
  }, [reviewText]);

  return (
    <div className="relative rounded-2xl bg-white p-4 sm:p-5 border border-slate-200/80 shadow-md shadow-slate-200/50 transition-all duration-200 focus-within:border-amber-400 focus-within:ring-2 focus-within:ring-amber-400/30">
      <div className="flex items-center justify-between pb-2 mb-2 border-b border-slate-100">
        <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-amber-700 bg-amber-50 px-2.5 py-1 rounded-md border border-amber-200/60">
          <Sparkles className="w-3.5 h-3.5 text-amber-500" />
          <span>Your Prepared Review</span>
        </div>
        <div className="flex items-center gap-1 text-xs text-slate-400 font-medium">
          <Edit3 className="w-3.5 h-3.5 text-slate-400" />
          <span>Tap text to edit</span>
        </div>
      </div>

      <textarea
        ref={textareaRef}
        value={reviewText}
        onChange={(e) => onChangeText(e.target.value)}
        placeholder="Select options below to build your review or type here..."
        className="w-full text-slate-800 text-base leading-relaxed font-medium bg-transparent border-0 focus:ring-0 focus:outline-none resize-none p-1 placeholder:text-slate-400"
        aria-label="Editable review text"
        rows={4}
      />

      <div className="mt-2 text-right">
        <span className="text-[11px] font-medium text-slate-400">
          {reviewText.length} characters
        </span>
      </div>
    </div>
  );
}
